# Your Website Title
title: 萌门

# Your Website URL
url: 'http://moedoor.live'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: 萌门
tagline: 我们都爱ZMC！
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: 打倒这个旧世界！
#description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
#email: you.email.email@gmail.com
#website: melvinchng.github.io # do not add http://
#linkedin: realmelvinchng
#github: melvinchng
#twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
